apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-2
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/data/pv-1
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: met-art-logs1
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: infer-service1
spec:
  type: NodePort
  selector:
    app: finalapp
  ports:
  - name: img-port
    protocol: TCP
    nodePort: 30010
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infer-deploy1
  labels:
    app: finalapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finalapp
  template:
    metadata:
      labels:
        app: finalapp
    spec:
      containers:
      - name: webserver1
        image: jjsbanana/final_demo:latest
        volumeMounts:
        - name: model-logs
          mountPath: /logs
        ports:
        - containerPort: 5000
        command:
        - "python"
        - "/app/main.py"
      volumes:
      - name: model-logs
        persistentVolumeClaim:
          claimName: met-art-logs1
      restartPolicy: Always

